name: Build VBA
on:
  - workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Build VBA-Enabled Workbook"
        uses: DecimalTurn/VBA-Build@7192dd34a5149d959d2f3f79825290de14fa86d1 #v0.1.0
      - name: "Push content"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add -v . || true
          
          git status
          if [ -n "$(git diff --cached --exit-code)" ]; then
            echo "Changes detected"
            commit_message=$(printf "File creation\n\nGitHub Action: %s/%s/actions/runs/%s" "${{ github.server_url }}" "${{ github.repository }}" "${{ github.run_id }}")
            git commit -m "$commit_message"        
            git push
          else
            echo "No changes to commit"
          fi
        shell: bash
